import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://join.riwi.io/register');
  await page.getByText('Nombre').click();
  await page.getByRole('textbox', { name: 'Introduce tu nombre' }).click();
  await page.getByRole('textbox', { name: 'Introduce tu nombre' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Introduce tu nombre' }).fill('N');
  await page.getByRole('textbox', { name: 'Introduce tu nombre' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Introduce tu nombre' }).fill('Nicolas');
  await page.getByText('Apellido').click();
  await page.getByText('Apellido').click();
  await page.getByRole('textbox', { name: 'Introduce tu apellido' }).click();
  await page.getByRole('textbox', { name: 'Introduce tu apellido' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Introduce tu apellido' }).fill('L');
  await page.getByRole('textbox', { name: 'Introduce tu apellido' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Introduce tu apellido' }).fill('Luna ');
  await page.getByRole('textbox', { name: 'Introduce tu apellido' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Introduce tu apellido' }).fill('Luna R');
  await page.getByRole('textbox', { name: 'Introduce tu apellido' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Introduce tu apellido' }).fill('Luna Romero');
  await page.getByText('Correo electrónico').click();
  await page.getByRole('textbox', { name: 'ejemplo@correo.com' }).click();
  await page.getByRole('textbox', { name: 'ejemplo@correo.com' }).fill('nicolasluna@example.com');
  await page.getByText('Usuario de Discord (Opcional)').click();
  await page.getByRole('textbox', { name: 'usuario#' }).click();
  await page.getByRole('textbox', { name: 'usuario#' }).fill('nicolas#3456');
  await page.getByText('Contraseña').click();
  await page.getByRole('textbox', { name: 'Min. 8 caracteres' }).click();
  await page.getByRole('textbox', { name: 'Min. 8 caracteres' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Min. 8 caracteres' }).fill('Q');
  await page.getByRole('textbox', { name: 'Min. 8 caracteres' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Min. 8 caracteres' }).fill('Qwerty123*');
  await page.getByText('Número Telefónico').click();
  await page.getByRole('textbox', { name: '3208753487' }).click();
  await page.getByRole('textbox', { name: '3208753487' }).fill('3133822741');
  await page.getByPlaceholder('DD/MM/AAAA').fill('2009-12-14');
  await page.getByText('Tipo de Documento').click();
  await page.locator('#idType').selectOption('Tarjeta de identidad');
  await page.getByRole('textbox', { name: '1234567890' }).click();
  await page.getByRole('textbox', { name: '1234567890' }).fill('1005752914');
  await page.getByText('Género').click();
  await page.locator('#gender').selectOption('Masculino');
  await page.getByText('Tipo de Convenio').click();
  await page.locator('#conventionType').selectOption('Medellín Joven');
  await page.getByRole('button', { name: 'Siguiente' }).click();
  await page.locator('#district').selectOption('ANTIOQUIA');
  await page.locator('#city').selectOption('ENVIGADO');
  await page.getByText('Sede de interes').click();
  await page.locator('#site').selectOption('Medellin');
  await page.getByText('Estrato Socioeconómico').click();
  await page.locator('#socialStatus').selectOption('5');
  await page.getByText('¿Qué horario tienes').click();
  await page.locator('#schedule').selectOption('Afternoon');
  await page.getByText('Medio de comunicación').click();
  await page.locator('#bestContact').selectOption('Correo electrónico');
  await page.getByRole('button', { name: 'Siguiente' }).click();
  await page.getByText('¿Nivel educativo alcanzado?').click();
  await page.locator('#degree').selectOption('Technologist');
  await page.getByRole('textbox', { name: 'Bachiller' }).click();
  await page.getByRole('textbox', { name: 'Bachiller' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Bachiller' }).fill('A');
  await page.getByRole('textbox', { name: 'Bachiller' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Bachiller' }).fill('Analisis de ');
  await page.getByRole('textbox', { name: 'Bachiller' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Bachiller' }).fill('Analisis de D');
  await page.getByRole('textbox', { name: 'Bachiller' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Bachiller' }).fill('Analisis de Datos');
  await page.getByText('Conocimientos en programación', { exact: true }).click();
  await page.locator('#programmingLevel').selectOption('Intermediate');
  await page.getByText('¿Qué ocupación tienes').click();
  await page.locator('#occupation').selectOption('Freelancer');
  await page.getByRole('checkbox', { name: 'He leído y acepto la Política' }).check();
  await page.getByRole('checkbox', { name: 'Acepto los Términos de uso' }).check();
  await page.getByRole('button', { name: 'Guardar' }).click();
});