import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://qa.talent.riwi.io/es/login');
  await page.getByTestId('login-input-email').click();
  await page.getByTestId('login-input-email').fill('nicomercial@bbl');
  await page.getByText('Español¡Bienvenido/a de nuevo').click();
  await page.getByTestId('login-input-email').click();
  await page.getByTestId('login-input-password').dblclick();
  await page.getByTestId('login-input-email').click();
  await page.getByTestId('login-input-email').click();
  await page.getByTestId('login-input-email').fill('nicomercial@example.com');
  await page.getByTestId('login-input-email').press('Tab');
  await page.getByTestId('login-input-password').press('CapsLock');
  await page.getByTestId('login-input-password').fill('P');
  await page.getByTestId('login-input-password').press('CapsLock');
  await page.getByTestId('login-input-password').fill('P4ssw0rd');
  await page.getByTestId('login-input-password').press('Enter');
  await page.getByTestId('login-button-toggle-password-visibility').click();
  await page.getByTestId('login-button-submit').click();
  await page.getByRole('button', { name: 'Nueva solicitud' }).click();
  await page.getByRole('textbox', { name: 'Título del cargo *' }).click();
  await page.getByRole('textbox', { name: 'Título del cargo *' }).fill('test');
  await page.getByRole('textbox', { name: 'Título del cargo *' }).press('Tab');
  await page.getByRole('combobox', { name: 'Seniority *' }).press('Tab');
  await page.getByRole('textbox', { name: 'Descripción del cargo *' }).fill('test');
  await page.getByRole('textbox', { name: 'Descripción del cargo *' }).press('Tab');
  await page.getByRole('button', { name: 'Crear nueva empresa' }).press('Enter');
  await page.getByRole('button', { name: 'Crear nueva empresa' }).press('Enter');
  await page.getByRole('button', { name: 'Crear nueva empresa' }).click();
  await page.getByRole('textbox', { name: 'Nombre de la empresa *' }).click();
  await page.getByRole('textbox', { name: 'Nombre de la empresa *' }).fill('test');
  await page.getByRole('textbox', { name: 'Email de servicio *' }).click();
  await page.getByRole('textbox', { name: 'Email de servicio *' }).fill('test@gmail.com');
  await page.getByRole('textbox', { name: 'Email de servicio *' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Email de servicio *' }).press('ControlOrMeta+c');
  await page.getByRole('textbox', { name: 'Email comercial (Opcional)' }).click();
  await page.getByRole('textbox', { name: 'Email comercial (Opcional)' }).fill('test@gmail.com');
  await page.getByRole('textbox', { name: 'Email administrativo (' }).click();
  await page.getByRole('textbox', { name: 'Email administrativo (' }).fill('test@gmail.com');
  await page.getByRole('textbox', { name: '3152345678' }).click();
  await page.getByRole('textbox', { name: '3152345678' }).fill('3135443356');
  await page.getByRole('textbox', { name: 'NIT (Id empresa) *' }).click();
  await page.getByRole('textbox', { name: 'NIT (Id empresa) *' }).fill('10113920873');
  await page.getByRole('combobox').filter({ hasText: 'Seleccionar industria...' }).click();
  await page.getByRole('option', { name: 'Fintech Servicios financieros' }).click();
  await page.getByRole('textbox', { name: 'Descripción de la empresa (' }).click();
  await page.getByRole('textbox', { name: 'Descripción de la empresa (' }).fill('test');
  await page.getByRole('combobox', { name: 'Tipo de contrato' }).click();
  await page.getByRole('option', { name: 'Staffing' }).click();
  await page.getByRole('combobox', { name: 'Tipo de contrato' }).click();
  await page.getByRole('option', { name: 'Contratación directa' }).click();
  await page.getByText('Nivel de inglés', { exact: true }).click();
  await page.locator('#radix-_r_10_').getByText('A1 - PrincipianteA2 - Bá').click();
  await page.getByRole('combobox').filter({ hasText: 'Avanzado' }).click();
  await page.getByRole('option', { name: 'Intermedio' }).click();
  await page.getByText('Buscar skills...10').click();
  await page.getByRole('button', { name: 'Excel' }).click();
  await page.getByText('Buscar skills...10').click();
  await page.getByRole('button', { name: 'Playwright' }).click();
  await page.getByText('Buscar skills...10').click();
  await page.getByRole('button', { name: 'Delphi' }).click();
  await page.getByRole('textbox', { name: 'Salario talento' }).click();
  await page.getByRole('textbox', { name: 'Salario talento' }).fill('$ 1.800.0000');
  await page.getByRole('spinbutton', { name: 'Número de vacantes' }).click();
  await page.getByRole('textbox', { name: 'Propósito del rol (Opcional)' }).click();
  await page.getByRole('textbox', { name: 'Propósito del rol (Opcional)' }).fill('test');
  await page.getByRole('textbox', { name: 'Relaciones laborales (' }).click();
  await page.getByRole('textbox', { name: 'Relaciones laborales (' }).click();
  await page.getByRole('textbox', { name: 'Relaciones laborales (' }).fill('test');
  await page.getByRole('textbox', { name: 'Responsabilidades principales' }).click();
  await page.getByRole('textbox', { name: 'Responsabilidades principales' }).fill('test');
  await page.getByRole('button', { name: 'Enviar solicitud' }).click();
  await page.getByRole('textbox', { name: 'Email administrativo (' }).dblclick();
  await page.getByRole('textbox', { name: 'Email administrativo (' }).click();
  await page.getByRole('textbox', { name: 'Email administrativo (' }).click();
  await page.getByRole('textbox', { name: 'Email administrativo (' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email administrativo (' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email administrativo (' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email administrativo (' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email administrativo (' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email administrativo (' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email administrativo (' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email administrativo (' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email administrativo (' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email administrativo (' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email administrativo (' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email administrativo (' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Email administrativo (' }).fill('test2@gmail.com');
  await page.getByRole('textbox', { name: 'Email de servicio *' }).click();
  await page.getByRole('textbox', { name: 'Email de servicio *' }).press('ArrowDown');
  await page.getByRole('textbox', { name: 'Email de servicio *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email de servicio *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email de servicio *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email de servicio *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email de servicio *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email de servicio *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email de servicio *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email de servicio *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email de servicio *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email de servicio *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email de servicio *' }).fill('test@gmail.com');
  await page.getByRole('textbox', { name: 'Email de servicio *' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Email de servicio *' }).fill('test3@gmail.com');
  await page.getByRole('textbox', { name: 'Email de servicio *' }).press('Tab');
  await page.getByRole('combobox').filter({ hasText: '+57 Colombia' }).press('Tab');
  await page.getByRole('textbox', { name: 'Email comercial (Opcional)' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Email comercial (Opcional)' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email comercial (Opcional)' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email comercial (Opcional)' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email comercial (Opcional)' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email comercial (Opcional)' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email comercial (Opcional)' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email comercial (Opcional)' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email comercial (Opcional)' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email comercial (Opcional)' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email comercial (Opcional)' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email comercial (Opcional)' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email comercial (Opcional)' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Email comercial (Opcional)' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Email comercial (Opcional)' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email comercial (Opcional)' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Email comercial (Opcional)' }).fill('test4@gmail.com');
  await page.getByRole('button', { name: 'Enviar solicitud' }).click();
  await page.getByRole('textbox', { name: 'NIT (Id empresa) *' }).click();
  await page.getByRole('textbox', { name: 'NIT (Id empresa) *' }).fill('1011392087');
  await page.getByRole('button', { name: 'Enviar solicitud' }).click();
});